version: '2.1'

services:

  fileserver:
    container_name: book_fileserver
    build:
      context: ./FileServer/
      dockerfile: Dockerfile    

    ports:
      - "5555:5555"
    volumes:
      - ./FileServer/appcode:/usr/src/app/ 
      - ../../../../../Book:/usr/src/book/
    
  # dashboard:
  #   container_name: book_dashboard
  #   build:
  #     context: ./Dashboard/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"

  #   volumes:
  #     - ./Dashboard/appcode:/usr/src/app/
